# Generated by Django 2.2 on 2019-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='project',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
